### PR TITLE
Fixed Pyflakes errors.

### PR DESCRIPTION
**Pull request by smartnavdeep**
# Hi Ved,

Ok, so as I was seeing the code, there are some `grammar mistakes`. In Programming too we have to code according to the rules of grammar (syntax, but this is not related to the syntax).

So there is something known as pyflakes and we need to code like that. Here are some rules which the code has not followed..

- Firsts things first, all the imports must be on the top of the code and each and every module import must be called first it self and cannot contain any comments between.

Like in the main file
```python
# Instead of
1.import something....
2.
3. # increasing the DPI settings
4.import ctypes
5.Something goes here
```

It should be like
```python
import something
import ctypes

# increasing the DPI settings
print('this is a nice program')
```

- Rule Two, whenever you are defining any class or function, you should leave two empty lines before and after them.

Like this
```python
# Line One
2.
3.
4.def  function(params):
      pass
5.
6.
print('That's good')
```

- Rule Three, According to the pyflakes  rules, there should not be and 'empty' line in the end of the file, but that problem will be auto fixed by GitHub

Ok so now the new question arises why is it necessary and how did programs run before. Actually python corrects it-self and when it can't it throws the syntax error, but when the program corrects itself, it might be delayed by milliseconds (I don't really know that it does, but the rules are true). 

So that's it for now, and I didn't actually mess with any GUI stuff or alike, but even I'm pretty not sure that did I do something to the code, so I recommend you to check the fork of mine and also test it, even though everything is good from my side.

Regards,
Navdeep.

### CODE REVIEW

**Comment by smartnavdeep** [comment]
good, but is the program working ?

**Comment by Ved-programmer** [comment]
yes, I am in the process of checking that

**Comment by Ved-programmer** [comment]
yes it is working perfectly fine! Great!

**Comment by smartnavdeep** [comment]
# 🎉

**Pull request merged**
